spring:
  datasource:
    url: jdbc:mysql://localhost:3307/orders_db
    username: root
    password: PylaDeepthi@04
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082